version: '2.1'
services:

  mongo:
    image: mongo:5.0.8-focal
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: r6
  
  redis:
    image: redis:7.0.0-alpine
    container_name: redis
    restart: unless-stopped

  r6-discord-bot:
    restart: unless-stopped 
    image: pololacoste/r6-discord-bot
    container_name: r6-discord-bot
    environment: 
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - MONGO_URL=mongodb://root:password@mongo:27017/?ssl=false
      - REDIS_URL=redis://redis:6379
      - CACHING=true
    depends_on: 
      - mongo
      - redis

  